### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by patchlog** [Axel186/emailjs-and-webpack-example#1] opened 2018-07-04 01:55 UTC
I get this error: 
Module build failed: Error: Couldn't find preset "env" relative to directory ...
at emailjs-and-webpack-example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19

**Comment by Axel186** [comment] 2018-07-08 11:36
Will take a look soon, thanks for the report!

**Comment by Axel186** [comment] 2019-03-06 10:01
Can't reproduce the issue, closing it since it's very old.

**Closed as completed by Axel186** 2019-03-06 10:01 UTC
